### ISSUE TITLE
Missing top level navigation to public-CDs

### ISSUE THREAD

**Issue by mrmxf** [SMPTE/smpte-website-issues#1]
There should be a top level link. It's hard to find the Public CDs and when you get to the page, it looks like an interstitioal page until you hit page-down a couple of times or do a lot of scrolling.

This shoudl be a first class page to attact public omment.

Bruce

**Comment by palemieux** [comment]
This repo is not monitored. Issues related to the website should be filed at https://www.smpte.org/supporticket?hsLang=en.
