### ISSUE TITLE
Black home screen

### ISSUE THREAD

**Issue by LarsBrg** [SMPTE/smpte-website-issues#2]
iMacPro, MacOS 10.14.6, Safari 13 and 14, smpte.org

www.smpte.org is black
Search box is extremely wide
Text columns are extremely narrow
Excessive white space
The correct CSS seems to be loaded

<img width="972" alt="Unknown" src="https://user-images.githubusercontent.com/51421041/96026629-74ef0400-0df2-11eb-822a-9dc693402fe7.png">
<img width="1430" alt="Screen Shot 2020-10-13 at 6 20 38 AM" src="https://user-images.githubusercontent.com/51421041/96026778-b1226480-0df2-11eb-99e9-34f06b198d10.png">
<img width="1593" alt="Screen Shot 2020-10-13 at 6 15 39 AM" src="https://user-images.githubusercontent.com/51421041/96026835-bc759000-0df2-11eb-9c60-a12f940e5c47.png">
<img width="1092" alt="Screen Shot 2020-10-13 at 7 32 51 AM" src="https://user-images.githubusercontent.com/51421041/96026856-c7302500-0df2-11eb-9e28-91b6c5225f5e.png">

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
