### ISSUE TITLE
SMPTE.org home page is  black with widely separated text labels (Safari 14.0.2)

### ISSUE THREAD

**Issue by LarsBrg** [SMPTE/smpte-website-issues#20]
(Oops. This is a dup of Black home screen #2)

Please describe the problem including the expected response, the actual response, and steps to reproduce the problem, and include the following information:

1. Computer system MacOS
2. OS version 10.14.6
3. Web browser and its version info Safari 14.0.2 (14610.3.7.1.10)
4. Provide the name (title) of the page in which the issue was detected (if possible) smpte.org
5. Provide a link to the page where the issue was detected (if possible) not applicable
6. Provide a detailed description of the issue
7. The page is black with widely separated text labels, from the hamburger menu. Doesn't look like the same page in Chrome.
9. Search box is giant, too tall, compared to Chrome

Give the issue report a short and informative title to identify the problem in the list of issues.

<img width="2206" alt="main page" src="https://user-images.githubusercontent.com/51421041/105259201-6de13b80-5b2f-11eb-9204-b3ae9a0ebab0.png">

<img width="2493" alt="Search boxes" src="https://user-images.githubusercontent.com/51421041/105259054-265aaf80-5b2f-11eb-8976-10c14a527256.png">

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
