### ISSUE TITLE
Why does swoogo & smpte plus not use SSO?

### ISSUE THREAD

**Issue by SMPTE-standards** [SMPTE/smpte-website-issues#21]
It's not obvious that plus.smpte.org needs the same password that swoogo.smpte.org uses for the plenary meetings. It's also not obvious why we don't have single sign on so that a password manager can automatically pick up the same password for all subdomains of smpte.org.

**Comment by tbause** [comment]
The commenter can not be identified. Further inquiries can't be conducted.

**Comment by SMPTE-TC** [comment]
SMPTE-TC is the Standards Vice President login. The name is historical from when github was set up. I'll try and change it when I get a spare second. The comment still stands. It's surprising when I update my login for the SMPTE site that it doesn't ripple through the other componenets of SMPTE

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
