### ISSUE TITLE
Inconsistent date / time data for events

### ISSUE THREAD

**Issue by SMPTE-standards** [SMPTE/smpte-website-issues#22]
There is no single place or workflow for ensuring that the date/time of events is consistent across all the platforms. I put together slides for the quarterly plenaries and quarterly webcasts and regularly come across different dates (e.g. how do I ensure that a plenary date change will ripple across swoogo, the website, any courses promoting it etc.). I don't know where to look for the canonical date, or how to get notified if it changes.

**Comment by tbause** [comment]
Your comment was ticketed and submitted to the website maintainer

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
