### ISSUE TITLE
No permalink to ER

### ISSUE THREAD

**Issue by palemieux** [SMPTE/smpte-website-issues#23]
The links to individual reports found on the [Reports page](https://www.smpte.org/technology-reports-downloads) are not permalinks and are not under a SMPTE controlled domain.

For example, SMPTE ER 1005:2021 is at [https://f.hubspotusercontent00.net/hubfs/5253154/er1005-2021.pdf](https://f.hubspotusercontent00.net/hubfs/5253154/er1005-2021.pdf)

**Comment by tbause** [comment]
Your comment was ticketed and submitted to the website maintainer

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
