### ISSUE TITLE
MONTHLY E-NEWSLETTER redirects to HubSpot login

### ISSUE THREAD

**Issue by palemieux** [SMPTE/smpte-website-issues#24]
The [MONTHLY E-NEWSLETTER _read more_](https://www.smpte.org/publications/newsletters-opinions) button:

![image](https://user-images.githubusercontent.com/4871350/126003363-69c240bb-193f-43d2-92d6-7bcbcd941e90.png)

redirects to:

![image](https://user-images.githubusercontent.com/4871350/126003396-0b04fabb-9c15-4eca-8489-87295ad8a2f9.png)

**Comment by tbause** [comment]
Can you let us know the month of the newsletter. I looked at the last 3 and could not see that behavior.

**Comment by palemieux** [comment]
When I click on the link I am redirected to:

![image](https://user-images.githubusercontent.com/4871350/126816178-b37caec4-a503-4297-a209-37452892bd7f.png)

**Comment by tbause** [comment]
Interesting, when I click the link it works and it brings me to the news letter. Which browser are you using?

**Comment by tbause** [comment]
Your comment was ticketed and submitted to the website maintainer

**Comment by palemieux** [comment]
> Interesting, when I click the link it works and it brings me to the news letter. Which browser are you using?

Version 91.0.4472.164 (Official Build) (64-bit)
Windows 10

**Comment by palemieux** [comment]
Looks like this was fixed.
