### ISSUE TITLE
Old link to Projects

### ISSUE THREAD

**Issue by thomasheritage** [SMPTE/smpte-website-issues#26]
https://www.smpte.org/2020-standard-policies-and-governance says:

> To do work in SMPTE, you need to create a [Project](https://kws.smpte.org/higherlogic/ws/public/projects) for each document created.

The link is to https://kws.smpte.org/higherlogic/ws/public/projects rather than https://www.smpte.org/projects

**Comment by palemieux** [comment]
@thomasheritage Issues related to the website should be filed at https://www.smpte.org/supporticket?hsLang=en. 

No one monitors this repo, which I plan to close later today.

**Comment by thomasheritage** [comment]
Thanks for the info -- I'll re-post as support tickets.
