### ISSUE TITLE
Recursive redirect

### ISSUE THREAD

**Issue by thomasheritage** [SMPTE/smpte-website-issues#27]
Visiting `http://x.smpte.org` causes a redirect to `http://www.x.smpte.org` if `x.smpte.org` is not a valid address (where `x` can be any text). So, this causes an infinite loop with the browser trying  to redirect to addresses such as `http://www.www.www.www.www.www.www.www.www.www.www.www.www.www.www.www.www.www.www.x.smpte.org/`

**Comment by palemieux** [comment]
@thomasheritage Issues related to the website should be filed at https://www.smpte.org/supporticket?hsLang=en.

No one monitors this repo, which I plan to close later today.

**Comment by thomasheritage** [comment]
Thanks for the info -- I'll re-post as support tickets.
