### ISSUE TITLE
AG/OM Links changed

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-website-issues#3]
All the saved links (using AG06 as example) have been changes such as:

- https://www.smpte.org/sites/default/files/AG-06-Starting-a-Project.docx
- https://f.hubspotusercontent00.net/hubfs/5253154/Standards%20Files/AG-06-Starting-a-Project.docx

At minimum redirects should be re-directed. This is not trivial - as some people have bookmarks, or in my case my the media standards registry I have https://stevellamb.github.io/mediastandards-registry/ has now all broken links to all SMPTE AG and OM documents.

**Comment by SteveLLamb** [comment]
On a few more passes to other pages, this seems to be the same with all links from the old version of the site. Such as quarterly reports, disclaimers, forms, etc.

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
