### ISSUE TITLE
Find a document page - not user friendly

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-website-issues#4]
https://www.smpte.org/standards/document-index

For document types (such as Standards Index) at the top of the page several issues:
- Clicking on a "Learn More" opens in a new tab/window
- It's not apparent at first look the page actually changed without having to scroll down a full page and half (1200 px?). There is too much wasted white space and the navigation doesn't "appear" to work from UX perspective, which is really bad practice.

**Comment by tbause** [comment]
Button has been changed to "Browse below". Clicking of the link will bring you to the top of the list on the page. Scrolling is not needed anymore. This is a workaround and the document type menu will be made more user friendly.

**Comment by SteveLLamb** [comment]
Much better!
