### ISSUE TITLE
Internal links - new tab

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-website-issues#6]
All internal site links many pages seem to constantly be opening new windows/tabs. Just casually browsing through the various pages for a few minutes, I had over 20 tabs open from this. 

- ALL internal SMPTE.org site links should open in the same tab. External links such as IEEE or elsewhere new tabs fine, but not internal.

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
