### ISSUE TITLE
Missing webcasts/newswatches

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-website-issues#7]
Past webcasts have URLs changed, and all saved links are broken:
Old - https://www.smpte.org/webcast/blahblahblah
New - https://www.smpte.org/events/blahblahblah

Past Newswatches URL changed as well:
https://www.smpte.org/publications/newswatch-X-XX
https://www.smpte.org/blog/title

No past Newswatches have been loading in from prior to Nov 2019.

Just to note, there are loads of organizations that link to both of these items internally for information about what SMPTE is doing (esp by their members that participate in SMPTE), and also for cross promotion and basic informational training, as well as historical industry background information. 

Auto-redirects for directories should be done at minimum, or hard redirects if page name is different. Past Newswatches should be loaded into the "blog".

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
