### ISSUE TITLE
Download link missing for Engineering Reports

### ISSUE THREAD

**Issue by tbause** [SMPTE/smpte-website-issues#8]
Windows 10 on Surface Book 3
Edge and Google Chrome

On the "Find a Document" webpage when clicking on browse below for Engineering Reports an list of engineering reports appears but no link to download the report is available. 

https://www.smpte.org/standards/reports#listing

**Comment by tbause** [comment]
Update: An access reports button was added to the page which brings a user to another page where ER's can be downloaded

**Comment by palemieux** [comment]
This repo is not monitored. The issue should be reported at https://www.smpte.org/supporticket?hsLang=en if still relevant.
