### ISSUE TITLE
Engineering Reports - Access Report is broken

### ISSUE THREAD

**Issue by LeighWhitcomb** [SMPTE/smpte-website-issues#9]
You cannot download the Engineering reports.

Goto www.smpte.org/standards/reports . Click on the “Access Reports” button and I get the error “We are Unable to Provide You Access to This Page”. I’m logged into my SMPTE account. I tested from 2 different computers and got the same issue.

1. Computer system
          Windows
2. OS version
          Windows 10
3. Web browser and its version info
          Firefox 81.0.2 (64-bit)
4. Provide the name (title) of the page in which the issue was detected (if possible)
         Engineering Reports
5. Provide a link to the page where the issue was detected (if possible)
         www.smpte.org/standards/reports
6. Provide a detailed description of the issue
         Click on the “Access Reports” button and I get the error “We are Unable to Provide You Access to This Page”. 

Give the issue report a short and informative title to identify the problem in the list of issues.
         Engineering Reports - Access Report is broken

**Comment by tbause** [comment]
This was fixed.
